### PR TITLE
Added phpcs

### PR DESCRIPTION
**Pull request by CZechBoY**
Hi,
I as we discussed in phpstan PR, I prepared PR for phpcs (coding standard check in TravisCI).
I found some serious bugs in case declaration, see Bug.class.php diff for example.

### CODE REVIEW

**Comment by CZechBoY** [comment]
Check TravisCI job at my account https://travis-ci.org/CZechBoY/stk-addons/jobs/402296085

**Comment by CZechBoY** [comment]
I rebased on current master and changed line endings to LF everywhere.

**Comment by leyyin** [comment]
Looks good, you know why the PHPUnit reports  `There were 24 risky tests:` ? https://travis-ci.org/CZechBoY/stk-addons/builds/403189605

**Comment by CZechBoY** [comment]
That is because of previous (phpstan) pr. It is because there is no assert in test case methods.

**Comment by leyyin** [comment]
Thanks.

**Pull request merged**
