### PR TITLE
Recursive addon files

### PR DESCRIPTION
**Pull request by Benau**
After this pr, stk-addons will auto "toggle" to the current subfolder (first folder to have any file (non-directories)):

Screenshot_20191208_023747

It will also remove any invalid files and report missing textures recursively (the webp files upload will be removed, the empty folder left will also be removed)

### CODE REVIEW

**Comment by vampy** [comment]
I don't understand the explanation, this basically removes the need for flattening so directories can have the same structure?

Also I don't get why in your screenshot the archive contains `canyon42/canyon42`

Also did you test this?

**Comment by Benau** [comment]
Kind of

```canyon42/canyon42``` for demonstration purpose, so it can now "cd" to any subfolders until it finds a file.

Yes tested fully in my local stk-addons

**Comment by vampy** [comment]
Ok, so that is the file you upload to the server, how does it look after an upload? (aka what is the file that the stk client sees it), can it use it?

Otherwise the code looks fine to me.

**Comment by Benau** [comment]
It will be made zip-> libaray (folder) and then textures and models spm and xml.

("last" folder removed)

Which is just compatible with current uploaded archive

**Pull request merged**
